// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFuNjVqVHa9HLk0j9JyKOU_o0OJVwGNl0',
    appId: '1:37263062684:web:173d94f77bc865c2b7df59',
    messagingSenderId: '37263062684',
    projectId: 'chat-app-604d5',
    authDomain: 'chat-app-604d5.firebaseapp.com',
    storageBucket: 'chat-app-604d5.appspot.com',
    measurementId: 'G-2P7Y49LGCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF78xACM8LSLrJM4-ZpawWEBqEmoH9kYc',
    appId: '1:37263062684:android:03e753edaa98de98b7df59',
    messagingSenderId: '37263062684',
    projectId: 'chat-app-604d5',
    storageBucket: 'chat-app-604d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp1nVItbnfyZXInp3Lv6-F2pVicI9s-T0',
    appId: '1:37263062684:ios:3e07895b9accc784b7df59',
    messagingSenderId: '37263062684',
    projectId: 'chat-app-604d5',
    storageBucket: 'chat-app-604d5.appspot.com',
    iosClientId: '37263062684-k73ojne1f8urh6ce077tpvonfqvol0b4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
